# Generated by Django 3.2.8 on 2021-12-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_0_count', models.IntegerField(default=0)),
                ('option_1_count', models.IntegerField(default=0)),
                ('option_2_count', models.IntegerField(default=0)),
                ('option_3_count', models.IntegerField(default=0)),
                ('option_4_count', models.IntegerField(default=0)),
                ('option_5_count', models.IntegerField(default=0)),
                ('option_6_count', models.IntegerField(default=0)),
                ('option_7_count', models.IntegerField(default=0)),
                ('option_8_count', models.IntegerField(default=0)),
                ('option_9_count', models.IntegerField(default=0)),
                ('option_10_count', models.IntegerField(default=0)),
                ('option_11_count', models.IntegerField(default=0)),
                ('option_12_count', models.IntegerField(default=0)),
                ('option_13_count', models.IntegerField(default=0)),
                ('option_14_count', models.IntegerField(default=0)),
                ('option_15_count', models.IntegerField(default=0)),
            ],
        ),
    ]
