# Generated by Django 3.2.9 on 2021-11-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('a_uri', models.CharField(max_length=200)),
                ('a_genre', models.CharField(max_length=500)),
                ('a_pop', models.IntegerField()),
                ('a_img', models.ImageField(upload_to='')),
            ],
        ),
    ]
